import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],

    darkMode: "class",

    theme: {
        extend: {
            fontFamily: {
                sans: [
                    "Plus Jakarta Sans",
                    "Inter",
                    "ui-sans-serif",
                    "system-ui",
                    "sans-serif",
                ],
                "body-md": ["Plus Jakarta Sans"],
                "headline-sm": ["Plus Jakarta Sans"],
                "headline-lg-mobile": ["Plus Jakarta Sans"],
                "headline-xl-mobile": ["Plus Jakarta Sans"],
                "headline-md": ["Plus Jakarta Sans"],
                "headline-lg": ["Plus Jakarta Sans"],
                "headline-xl": ["Plus Jakarta Sans"],
                "label-lg": ["Plus Jakarta Sans"],
                "label-md": ["Plus Jakarta Sans"],
                "label-sm": ["Plus Jakarta Sans"],
                "body-sm": ["Plus Jakarta Sans"],
                "body-lg": ["Plus Jakarta Sans"],
                "title-md": ["Plus Jakarta Sans"],
                "title-lg": ["Plus Jakarta Sans"],
            },

            // Material 3-style tokens taken from the Booking Lapang Stitch design
            // ("Arena hijau tegas + terakota" theme). These are additive to the
            // legacy blue tokens below so nothing already in production breaks.
            colors: {
                background: "#fbf7f0",
                "surface-dim": "#dddad3",
                "on-tertiary-container": "#dcb85f",
                "on-secondary-fixed-variant": "#83260e",
                "surface-variant": "#e6e2db",
                "inverse-on-surface": "#f4f0e9",
                "secondary-fixed-dim": "#ffb4a2",
                "on-secondary-fixed": "#3c0700",
                "on-secondary-container": "#731a04",
                "on-secondary": "#ffffff",
                "error-container": "#ffdad6",
                "inverse-primary": "#99d4a4",
                "on-tertiary-fixed-variant": "#5a4400",
                "secondary-fixed": "#ffdad2",
                "surface-tint": "#326942",
                "on-primary-fixed": "#00210c",
                "on-background": "#1c1c18",
                "primary-fixed-dim": "#99d4a4",
                "surface-container-low": "#f7f3ec",
                "surface-container-high": "#ebe8e1",
                "surface-container": "#f1ede6",
                "tertiary-fixed-dim": "#e9c46a",
                "on-error": "#ffffff",
                "on-primary": "#ffffff",
                "surface-bright": "#fdf9f2",
                "on-primary-container": "#8fca9b",
                "on-tertiary": "#ffffff",
                "on-error-container": "#93000a",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed-variant": "#18512c",
                "primary-container": "#1e5631",
                "on-tertiary-fixed": "#251a00",
                "surface-container-highest": "#e6e2db",
                "inverse-surface": "#31302c",
                tertiary: "#443200",
                "tertiary-fixed": "#ffdf96",
                "tertiary-container": "#5f4800",
                "on-surface-variant": "#414941",
                "outline-variant": "#c0c9be",
                "primary-fixed": "#b5f1bf",
                "secondary-container": "#e76f51",

                // Corrected to the exact "Arena Hijau" spec from the Stitch design panel:
                // primary green #1E5631 / hover #3A7D44, terracotta accent #E76F51,
                // mustard #E9C46A, soft cream background #FBF7F0, ivory-white cards #FFFFFF.
                primary: {
                    DEFAULT: "#1e5631",
                    50: "#e9f2ec",
                    100: "#b5f1bf",
                    200: "#99d4a4",
                    300: "#8fca9b",
                    400: "#3a7d44",
                    500: "#1e5631",
                    600: "#18512c",
                    700: "#123d22",
                    800: "#0c2917",
                    900: "#00210c",
                },
                secondary: "#e76f51",
                error: "#ba1a1a",
                outline: "#717970",
                "on-surface": "#1c1c18",

                surface: {
                    DEFAULT: "#fbf7f0",
                    container: "#f1ede3",
                    "container-low": "#f6f2ea",
                    "container-high": "#ece7db",
                    "container-highest": "#e3ddcf",
                    "container-lowest": "#ffffff",
                    dim: "#ddd6c4",
                    bright: "#fbf7f0",
                    tint: "#3a7d44",
                    variant: "#e3ddcf",
                },
            },

            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                "2xl": "1rem",
                "3xl": "1.5rem",
                full: "9999px",
            },

            spacing: {
                18: "4.5rem",
                22: "5.5rem",
                26: "6.5rem",
                "margin-desktop": "3rem",
                "space-lg": "1.5rem",
                "space-2xs": "0.25rem",
                "space-3xl": "4rem",
                "margin-mobile": "1rem",
                "space-2xl": "3rem",
                "space-xs": "0.5rem",
                "gutter-sm": "1rem",
                "space-md": "1rem",
                "margin-tablet": "2rem",
                "gutter-lg": "1.5rem",
                "space-sm": "0.75rem",
                "space-xl": "2rem",
            },

            fontSize: {
                "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0.005em", fontWeight: "400" }],
                "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
                "headline-lg-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-xl-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "800" }],
                "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "700" }],
                "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-xl": ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "800" }],
                "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
                "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
                "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
                "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
                "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
                "title-md": ["16px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "600" }],
                "title-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }],
            },

            boxShadow: {
                "soft-sm": "0 1px 3px rgba(15, 23, 42, 0.06)",
                "soft-md": "0 4px 12px rgba(15, 23, 42, 0.08)",
                "soft-lg": "0 10px 30px rgba(15, 23, 42, 0.10)",
                "grass-resting": "0 2px 6px -1px rgba(27, 46, 31, 0.05), 0 1px 3px -1px rgba(27, 46, 31, 0.03)",
                "grass-interactive": "0 8px 16px -4px rgba(27, 46, 31, 0.08), 0 4px 6px -2px rgba(27, 46, 31, 0.04)",
                "grass-floating": "0 14px 28px -6px rgba(27, 46, 31, 0.12), 0 6px 12px -3px rgba(27, 46, 31, 0.06)",
            },

            maxWidth: {
                "8xl": "90rem",
            },
        },
    },

    plugins: [forms],
};